### ISSUE TITLE
Breaking on permissions

### ISSUE THREAD

**Issue by jwb009** [khalwat/generator-nystudio107#9]
Hello, I can't seem to get passed the permissions step when trying to install your generator

```
> Setting global permissions to 755 / 644
find: missing argument to `-exec'
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: find . -type f -exec chmod 644 {} \;
find: missing argument to `-exec'

    at checkExecSyncError (child_process.js:464:13)
    at Object.execSync (child_process.js:504:13)
    at module.exports.yo.generators.Base.extend.install (C:\Users\Joe\Sites\test\generator-craftinstall\app\index.js:301:23)
    at C:\Users\Joe\Sites\test\generator-craftinstall\node_modules\yeoman-generator\lib\base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Any ideas what could be wrong? I'm developing on Win 64, using git bash, if it matters. Thank you!

**Comment by ejaedesign** [comment]
If you're working locally on a Windows machine, the generator's attempt to set permissions will cause this error. This is due to the app/index.js executing Linux-based permission settings (of course, you won't need to set permissions locally on Windows). 

To work around the issue, simply comment out the lines 297-310 with the comment header "Set permissions on the entire Craft install tree" in the app/index.js file. 

Afterward, run 'yo craftinstall' command again and it should complete the generator.
